### ISSUE TITLE
Update the about section

### ISSUE THREAD

**Issue by ankiiitraj** [devfolioco/react-copy-mailto#27]
We now have URL for the demo and we can now add this to the about section of the repo 🎉 
[https://devfolioco.github.io/react-copy-mailto/](https://devfolioco.github.io/react-copy-mailto/)

**Comment by mdb571** [comment]
Can I work on this?

**Comment by naman360** [comment]
I am working on this.

**Comment by ankiiitraj** [comment]
> I am working on this.

Only the maintainer of this repo can do this 😕

**Comment by naman360** [comment]
Sorry for that  actually I saw one of the comments in which it was written person with first PR will be assigned, so I actually commented for PR. Sorry for behaviour

**Comment by ankiiitraj** [comment]
@naman360 there's some confusion here. By "Only the maintainer of this repo can do this" I meant this modification can only be performed by the maintainer. Like only the maintainer can edit this about section. See the screenshot for more clarification!
![Screenshot from 2020-10-01 23-25-21](https://user-images.githubusercontent.com/48787278/94845691-aaccd980-043d-11eb-87d9-13eb0e2cbbc0.png)

**Comment by adinalini** [comment]
I would like to work in this issue

**Comment by naman360** [comment]
Sorry I misunderstood :) I would love to work on it can you assign it to me.

**Comment by swapniljha001** [comment]
So, has this issue already been resolved?

**Comment by adinalini** [comment]
Yes @swapniljha001
