### ISSUE TITLE
README.md should have more info about malito links

### ISSUE THREAD

**Issue by sshiv5768** [devfolioco/react-copy-mailto#33]
Can I put a PR?

**Comment by knowyours** [comment]
Can I be assigned to work on this?

**Comment by frbio** [comment]
Brief me the details. I can work on this.

**Comment by vsasvipul0605** [comment]
I want to work on this. please assign this to me

**Comment by GoGi2712** [comment]
I will work on this and give you the best result.Please assign me this issue.
