### ISSUE TITLE
Host the demo and link it to the Readme

### ISSUE THREAD

**Issue by jai-dewani** [devfolioco/react-copy-mailto#46]
The demo can be hosted so people can directly interact with it and not have to download and run a local server to just see the library working, the same has been done by [react-opt-input](https://github.com/devfolioco/react-otp-input).

**Comment by ankiiitraj** [comment]
the demo is being hosted here : https://devfolioco.github.io/react-copy-mailto

**Comment by jai-dewani** [comment]
This isn't mentioned in the README, right?

**Comment by deepank120896** [comment]
> This isn't mentioned in the README, right?

@jai-dewani 
I have added the link to the Hosted location to the readme.

**Comment by jai-dewani** [comment]
Okay thanks, @deepank120896. I am then closing this issue.

**Comment by deepank120896** [comment]
@jai-dewani 
I think the issue should be closed after the merge of PR, as per good practice.

**Comment by deepank120896** [comment]
@jai-dewani I think you can go ahead and assign it to me or the person who would be reviewing

**Comment by deepank120896** [comment]
@jai-dewani 
https://github.com/devfolioco/react-copy-mailto/pull/50
Pull request is open

**Comment by jai-dewani** [comment]
I am just another contributor like you @deepank120896  
IDK who will be reviewing this issue nor do I have the access to assign it to anyone
