### ISSUE TITLE
Bug: tooklit text changes to copy email address even after copying, when focus is not moved from the email.

### ISSUE THREAD

**Issue by sanjayrajpurohit36** [devfolioco/react-copy-mailto#77]
I was working on issue #38 then I found that the toolkit text changes back to **copy email address** even after copying the email address when the focus is **not moved out** from the email.
Adding the gif to **demonstrate** the behavior.
![2020-10-16 11 49 56](https://user-images.githubusercontent.com/20855377/96220243-fd61d600-0fa5-11eb-8b5e-87240cec1dfd.gif)

**Comment by knit-to-code** [comment]
I made a PR (#80) that fixes this issue :)
