### ISSUE TITLE
Add a GitHub action to deploy the demo to GitHub pages

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/react-copy-mailto#8]
Integrate this [action](https://github.com/marketplace/actions/deploy-to-github-pages) to automatically build the demo and deploy on the gh-pages branch.

**Comment by juanbelieni** [comment]
I can work on this, could you assign me?

**Comment by prateek3255** [comment]
Sure go ahead!

**Comment by ankiiitraj** [comment]
I have a working solution for this issue! Can I make the PR? @prateek3255

**Comment by juanbelieni** [comment]
I haven't started yet, so you can assign @ankiiitraj.

**Comment by ankiiitraj** [comment]
Making a PR! Thanks @juanbelieni
