### ISSUE TITLE
Add a prop for light mode in the tooltip

### ISSUE THREAD

**Issue by prateek3255** [devfolioco/react-copy-mailto#9]
Currently, the tooltip has a light text on a dark background by default. Add a prop makes the tooltip to have a light background with dark text colour

**Comment by kala2** [comment]
Hi, could you assign to me please?

**Comment by sakshi-choudhary** [comment]
hey, I would like to work on this. could you assign me this?

**Comment by ankiiitraj** [comment]
Working on it!

**Comment by prateek3255** [comment]
Sure go ahead!

**Comment by lopeselio** [comment]
can i work on this?
